### ISSUE TITLE
No module named 'core'

### ISSUE THREAD

**Issue by akumareutre** [a-real-ai/pywinassistant#2]
Hello, I have this error do you have any issues of this ?
`Traceback (most recent call last):
  File "C:\Users\xxxx\Desktop\pywinassistant-Pre-Database\core\assistant.py", line 8, in <module>
    from core.voice import speaker, set_volume, set_subtitles
ModuleNotFoundError: No module named 'core'`

**Comment by saffie91** [comment]
Hey I'm not one of the devs but you should probably try running it like this:
python3 -m core.assistant
