### ISSUE TITLE
Running error message, indicating no database files

### ISSUE THREAD

**Issue by kkive** [a-real-ai/pywinassistant#4]
![image](https://github.com/a-real-ai/pywinassistant/assets/51246778/7db5d1ba-5df6-4b0b-8b86-e83c436c21d8)

Line 1086 in file driver.py
`    conn.commit()
    conn.close()
database_file = r'Database\history.db'
create_database(database_file)`
How can we solve this

**Comment by maryxyan** [comment]
Same problem any solutions?

**Comment by OumarDicko** [comment]
Same problem too
