### ISSUE TITLE
Make an install guide

### ISSUE THREAD

**Issue by natek000** [a-real-ai/pywinassistant#5]
Sure, enough, we've got two issues open:
["No module named core"](https://github.com/a-real-ai/pywinassistant/issues/2) and ["Running error message, indicating no database files"](https://github.com/a-real-ai/pywinassistant/issues/4)

The bottom line is that the installation/usage instructions are _terrible_. I'm trying to run this in a virtual environment and hitting both of these issues. There is no chance I'm running outside an environment given it breaks itself. If you want people to use your project, you need to figure out how to make it work simply on other machines, period!

This is a promising project. Fix the install guide or else no one will use it. Unbelievably lazy to provide zero installation instructions. I'm not interested in guessing what configuration you had on your machine, and neither is anyone else.

**Comment by henyckma** [comment]
I understand that fixing simple import paths and generating a new file can be challenging for automated virtual bot systems.

Back in 2023 I purposely added those issues to avoid automated virtual bot systems to take advantage of this project, thus avoiding bot usage from bad actors as I wanted true human reviewers to gain knowledge of this algorithm to check the actual code.

Now that this project gained relevance and is broadly public, those issues are no longer necessary to maintain off radar from automated virtual bot systems.

Thank you for the issue submitted and your time trying to fix those issues, expect the complete and easiest installation guide soon Q3 2024. Also I'm working on integrating it as a simple library install with PIP.

**Comment by henyckma** [comment]
@Razorbob thank you so much! You rock man! If you have further questions, issues or suggestions don't hesitate opening new threads in this repo. Thank you for your time.

**Comment by TheJustinCrow** [comment]
> move all the "core." from the imports

@Razorbob  Could you clarify this a bit? Going to try to get this running with Groq cloud, and can't even get it running at all yet. Also checked your PR.

**Comment by t0fum4n** [comment]
@henyckma came across this project today and I knew something was phishy when there was no history.db file. Nice work. Big fan.

**Comment by roberto-coscia** [comment]
where to insert the api keys?

**Comment by gnosisd** [comment]
> Installation instructions from my personal debugging. Download all move driver to core folder remove all the "core." from the imports install missing packages pyaudio create a file history.db in core folder an delete the database add your api keys make sure u have a billing plan on openai make sure you cd into core folder and start assistant.py

what do you mean delete the database? there is no database inside core or elsewhere.also where do we import the api keys? please can you make it more clear for people who are not that good at these things pls?

**Comment by eav-solution** [comment]
I created Database folder in core and put history.db into it.
